### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by KayNguyen97** [Jaammerr/MintChain-Bot#2]
![image](https://github.com/Jaammerr/MintChain-Bot/assets/126054099/f32f4b7f-8a63-447a-87bf-dfc3e0f05d69)
pls help solve

**Comment by Jaammerr** [comment]
Try to use a virtual enviroment:

1. python -m venv venv
2. cd venv/Scripts
3. activate
4. return to root dir
5. pip install -r requirements.txt
6. python run.py
