### ISSUE TITLE
Failed to complete tasks: {'error_code': 353, 'error_message': 'This request requires a matching csrf cookie and header.'} | Retrying..

### ISSUE THREAD

**Issue by flyrainsong** [Jaammerr/MintChain-Bot#5]
Failed to complete tasks: {'error_code': 353, 'error_message': 'This request requires a matching csrf cookie and header.'} | Retrying..

but twitter token is ok

**Comment by Jaammerr** [comment]
use the last version, swap your proxy or try another account
